### ISSUE TITLE
Does this work for video files?

### ISSUE THREAD

**Issue by gracejang** [nzkozar/ExoplayerExample#1]
Hello! Thank you for sharing this! I was wondering, does this for video files as well? (I noticed it mentions audio files)

If so, I think I am having an issue with it where I get this error. Any idea what this might be about?:

04-09 23:15:12.171 13469-16340/PACKAGE_NAME E/LoadTask: Unexpected exception loading stream
                                                                      java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=-8 dst.length=8192 dstPos=0 length=3192
                                                                          at java.lang.System.arraycopy(Native Method)
                                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:221)
                                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:191)
                                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:93)
                                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:104)
                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:262)
                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:148)
                                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:630)
                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by nzkozar** [comment]
Hi, I have not tried playing any video files with this, but I'd assume it wouldn't work since for starters you'd need to have a canvas for displaying the video in in addition to using a separate renderer for video, which this example does not have.

Below is a link to a project, by @Foso, I used as a basis for building my example. It shows how to play video from an URL, but you should be able to morph it into playing one from a local file:
https://github.com/Foso/ExoPlayer-with-MediaControls

Hope this helps
